name: Java CI with Maven

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
      AZURE_CONTAINER\_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
      DB_URI: ${{ secrets.DB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      RAZORPAY_KEY: ${{ secrets.RAZORPAY_KEY }}
      RAZORPAY_SECRET: ${{ secrets.RAZORPAY_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Test
        run: mvn test

      - name: Deploy
        run: mvn deploy